defmodule Problem12 do
  @moduledoc """
  https://projecteuler.net/problem=12

  Highly divisible triangular number


  The sequence of triangle numbers is generated by adding the natural numbers. 
  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
  The first ten terms would be:

  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

  Let us list the factors of the first seven triangle numbers:

       1: 1
       3: 1,3
       6: 1,2,3,6
      10: 1,2,5,10
      15: 1,3,5,15
      21: 1,3,7,21
      28: 1,2,4,7,14,28

  We can see that 28 is the first triangle number to have over five divisors.
  
  What is the value of the first triangle number to have over five hundred divisors?


  """

  @doc """


  """

  def find_divisors(n) do
    (for i <- 1..ceil(:math.sqrt(n)), rem(n,i)==0 do 
      i 
    end  |> length ) *2
  end

  def highly_divisible_triangle(n, min_ndivisors \\ 500)  do
    triangle = (n*(n+1)) |> div(2)
    ndivisors = triangle |> find_divisors
    res = if ndivisors >= min_ndivisors do
      triangle
    else
      highly_divisible_triangle(n+1, min_ndivisors) 
    end
    res
  end

end
